i added requirements and README
AnyaKononova/zadanie2 pull request #1
Opened 2023-09-25 06:55 UTC by AnyaKononova

2023-10-05 07:26 UTC, arybin93 requested changes

2023-10-05 07:26 UTC, arybin93 commented on requirements
> +numpy version 1.26.0
В таком формате сработает команда `pip install -r requirements.txt`?

2023-10-16 07:09 UTC, maks2035 approved these changes
мамамия, какой замечательный код

2023-10-16 07:10 UTC, merged

2023-10-16 08:53 UTC, AnyaKononova commented
Спасибо амиго!